# Examples-Tensorflow: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up
version: '3'
services:

  tensorflow:
    hostname: tensorflow
    ports:
      - "80:8000"
    restart: always
    image: tensorflow/tensorflow:1.0.0
    build:
      context: .
      dockerfile: docker/tensorflow/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
